name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:

  check-relayer:
    name: Release relayer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check
        run: |
          yarn install
          yarn build

