name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  release-relayer:
    name: Release relayer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2




